### PR TITLE
Delete obsolete symlinks

### LINKED ISSUE #3: Cleanup broken links instead of crashing
If a link is broken (underlying file has been deleted manually) in a periodic dir, program will crash at execution.
Would be better to dleete the link in such a case

### PR DESCRIPTION
**Pull request by 501st-alpha1**
Fixes #3.

### CODE REVIEW

**Comment by Kraymer** [comment]
Thks for addressing that ⚡ 
`file_create_day`possibly now returning `None` in `file_create_day` is a problem, no ?

**Comment by 501st-alpha1** [comment]
Oh yeah, I added a check for that in `archives_create_days`, but not in `delta_days`.  I *think* the `filename` used in `delta_days` should always be an existing file, but I'll add a check there too, just in case.

**Comment by 501st-alpha1** [comment]
I added that check to `delta_days`.  I had added one to `timed_symlink` as well, but that broke things, so I reverted it.  I've left the commits here for reference, but I can delete them before merging this branch so the history is cleaner.

**Comment by Kraymer** [comment]
Done by 186f3bc34f923b27b79b89b021641048080e5f96

I cannot merge that PR as I refactored the code aggressively this week, this case is covered by a test now.

**Pull request closed without merging**
